USE [master]
GO
/****** Object:  Database [PhonebookDb]    Script Date: 15/01/2026 5:46:14 PM ******/
CREATE DATABASE [PhonebookDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PhonebookDb', FILENAME = N'/var/opt/mssql/data/PhonebookDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PhonebookDb_log', FILENAME = N'/var/opt/mssql/data/PhonebookDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PhonebookDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PhonebookDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PhonebookDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PhonebookDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PhonebookDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PhonebookDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [PhonebookDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PhonebookDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PhonebookDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PhonebookDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PhonebookDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PhonebookDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PhonebookDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PhonebookDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PhonebookDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PhonebookDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PhonebookDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PhonebookDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PhonebookDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PhonebookDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PhonebookDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PhonebookDb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [PhonebookDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PhonebookDb] SET RECOVERY FULL 
GO
ALTER DATABASE [PhonebookDb] SET  MULTI_USER 
GO
ALTER DATABASE [PhonebookDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PhonebookDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PhonebookDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PhonebookDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PhonebookDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PhonebookDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PhonebookDb', N'ON'
GO
ALTER DATABASE [PhonebookDb] SET QUERY_STORE = ON
GO
ALTER DATABASE [PhonebookDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PhonebookDb]
GO
/****** Object:  Schema [contacts]    Script Date: 15/01/2026 5:46:15 PM ******/
CREATE SCHEMA [contacts]
GO
/****** Object:  Table [contacts].[ContactGroups]    Script Date: 15/01/2026 5:46:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [contacts].[ContactGroups](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](500) NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[CreatedOn] [datetime2](7) NULL,
	[UpdatedOn] [datetime2](7) NULL,
 CONSTRAINT [PK_ContactGroups] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [contacts].[Contacts]    Script Date: 15/01/2026 5:46:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [contacts].[Contacts](
	[Id] [uniqueidentifier] NOT NULL,
	[FirstName] [nvarchar](100) NOT NULL,
	[LastName] [nvarchar](100) NOT NULL,
	[PhoneNumber] [nvarchar](20) NOT NULL,
	[CountryCode] [nvarchar](5) NULL,
	[PhoneExtension] [nvarchar](10) NULL,
	[Email] [nvarchar](256) NULL,
	[Street] [nvarchar](200) NULL,
	[City] [nvarchar](100) NULL,
	[State] [nvarchar](100) NULL,
	[PostalCode] [nvarchar](20) NULL,
	[Country] [nvarchar](100) NULL,
	[Company] [nvarchar](200) NULL,
	[JobTitle] [nvarchar](100) NULL,
	[Notes] [nvarchar](1000) NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NULL,
	[IsFavorite] [bit] NOT NULL,
	[ContactGroupId] [uniqueidentifier] NULL,
	[CreatedOn] [datetime2](7) NULL,
	[UpdatedOn] [datetime2](7) NULL,
 CONSTRAINT [PK_Contacts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 15/01/2026 5:46:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_ContactGroups_Name]    Script Date: 15/01/2026 5:46:15 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_ContactGroups_Name] ON [contacts].[ContactGroups]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Contacts_ContactGroupId]    Script Date: 15/01/2026 5:46:15 PM ******/
CREATE NONCLUSTERED INDEX [IX_Contacts_ContactGroupId] ON [contacts].[Contacts]
(
	[ContactGroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Contacts_Email]    Script Date: 15/01/2026 5:46:15 PM ******/
CREATE NONCLUSTERED INDEX [IX_Contacts_Email] ON [contacts].[Contacts]
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Contacts_FirstName]    Script Date: 15/01/2026 5:46:15 PM ******/
CREATE NONCLUSTERED INDEX [IX_Contacts_FirstName] ON [contacts].[Contacts]
(
	[FirstName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Contacts_IsFavorite]    Script Date: 15/01/2026 5:46:15 PM ******/
CREATE NONCLUSTERED INDEX [IX_Contacts_IsFavorite] ON [contacts].[Contacts]
(
	[IsFavorite] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Contacts_LastName]    Script Date: 15/01/2026 5:46:15 PM ******/
CREATE NONCLUSTERED INDEX [IX_Contacts_LastName] ON [contacts].[Contacts]
(
	[LastName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [contacts].[ContactGroups] ADD  DEFAULT (newsequentialid()) FOR [Id]
GO
ALTER TABLE [contacts].[Contacts] ADD  DEFAULT (newsequentialid()) FOR [Id]
GO
ALTER TABLE [contacts].[Contacts]  WITH CHECK ADD  CONSTRAINT [FK_Contacts_ContactGroups_ContactGroupId] FOREIGN KEY([ContactGroupId])
REFERENCES [contacts].[ContactGroups] ([Id])
ON DELETE SET NULL
GO
ALTER TABLE [contacts].[Contacts] CHECK CONSTRAINT [FK_Contacts_ContactGroups_ContactGroupId]
GO
USE [master]
GO
ALTER DATABASE [PhonebookDb] SET  READ_WRITE 
GO
